### ISSUE TITLE
latest plugin version failes in gradle multi platform project

### ISSUE THREAD

**Issue by xoif** [AllBus/gradle-android-scala-plugin#2]
v. 3.3.2 of your Plugin leads every gradle task failing with the message:
Task with name 'processDebugResources' not found in project

Right now we use your scala plugin in a library submodule. Former versions with gradle 3.* built just fine, 3.2.0-M1 with gradle wrapper 4.9 and gradle 3.2.0 is working as well. 3.3.2 is failing for both gradle wrapper 4 and 5 with the error above

**Comment by AllBus** [comment]
This is due to the fact that the task of compilation scala must be performed after the task 'processDebugResources'. This task is missing when compiling submodules.

Workaround temporary solution create empty 'processDebugResources' and 'processReleaseResources' tasks in gradle file of submodule.


	task processDebugResources(){
	}
	
	task processReleaseResources(){
	}

**Comment by xoif** [comment]
Thank you very much for the fast fix. Whereas my Scala modules will now build with v3.4.0  and gradle 5.3, my activities written in scala will crash at runtime while inflating resources. 
This seems to be a general resource linking problem, as every resource id that has been referenced in scala, - e.g. findViewById(R.id.xyz) - will return null.  
This will lead to  `android.content.res.Resources$NotFoundException` exception as soon as the content view should be inflated in setContentView(R.layout.xyz). 

As the same code works fine with 3.2.0-M1, gradle tool 3.2.0 and gradle 4.9, there must be some bug within compiling the resources or linking them. 
Again, this happens in my project using submodules, using the android default folder structure (with resources in /<submodule-name>/src/main/res)

**Comment by mx-tc** [comment]
So to us: we have a project that constists of multiple gradle-submodules (one of type android-application and multiple of android-library).
one of those android-library submodules uses the _gradle-scala-plugin_. building succeeds but we are getting a runtime-exception of kind `android.content.res.Resources$NotFoundException` when calling e.g. `setConentView(R.layout.our_activity)` from `onCreate`

Gradle-Version: gradle-5.6.3
Gradle-Plugin-Versions: 
- 'com.android.tools.build:gradle:3.5.2'
- 'com.github.AllBus:gradle-android-scala-plugin:3.5.1'

it seems the resource-ids get regenerated during packaging and therefor don't match those within the compiled classes. 
when looking in the generated AAR-file from `<submodule>/build/outputs/aar/` there is a file `R.txt` which holds the resource-id that is causing the crash, but the according generated `R.java` file in the app-build-directory (`app/build/generated/not_namespaced_r_class_sources/debug/r/com/mobiworx/<submodule>/`) holds a different resource-id for the same resource.
