### ISSUE TITLE
Compilation error details are not provided

### ISSUE THREAD

**Issue by akumaigorodski** [AllBus/gradle-android-scala-plugin#6]
When compiling a project with some kind of error (say, a mistyped variable name in Scala, but not in Java file) a Build Output only gives a general `Compilation failed` and `org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugScala'` without pointing to exact place or detailed error description. Any hints on how can this be fixed?

My (possible relevant) setup:
```
Android Studio 3.5.3
openjdk 11.0.5 2019-10-15
classpath 'com.android.tools.build:gradle:3.5.3'
classpath 'com.github.AllBus:gradle-android-scala-plugin:3.5.1'
```

**Comment by AllBus** [comment]
![изображение](https://user-images.githubusercontent.com/17080262/72217586-6dd85400-3549-11ea-97eb-3c0083a75484.png)

In build output window in the left toolbar click button "Toggle view"

**Comment by akumaigorodski** [comment]
Thanks, problem solved!
